# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build Simple App

on:
 push:
  branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Week4/simple-app
          file: Dockerfile
          push: true
          tags: officialdarnyc/simple-app:v1